<?php
if(($permissao['mk1']??'N') == S){
$empresa=(int)$_SESSION['empresa'];
$lista=$mysqli->query("SELECT * FROM servidores WHERE tiporouter='MIKROTIK' AND empresa='$empresa' ORDER BY servidor");
$total=$lista?$lista->num_rows:0;$online=0;$offline=0;
if($lista){$lista->data_seek(0);while($z=$lista->fetch_assoc()){@$s=fsockopen($z['ip'],8728,$e,$er,1);if($s){$online++;fclose($s);}else{$offline++;}}$lista->data_seek(0);}
?>
<style>
.mrn{font-family:Arial,sans-serif}.mrn-head{background:linear-gradient(135deg,#17283f,#1769bd);color:#fff;border-radius:12px;padding:22px;margin-bottom:15px;display:flex;justify-content:space-between}.mrn-head h1{margin:0;font-size:25px}.mrn-head p{margin:4px 0 0;opacity:.8}.mrn-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-bottom:15px}.mrn-stat,.mrn-box{background:#fff;border:1px solid #e5ebf3;border-radius:12px;padding:15px;box-shadow:0 2px 12px #17283f0d}.mrn-stat span{display:block;color:#718096;font-size:11px}.mrn-stat b{font-size:25px;color:#17283f}.mrn-table th{background:#f6f9fc;color:#526174;font-size:12px}.mrn-table td{vertical-align:middle}.mrn-dot{display:inline-block;width:9px;height:9px;border-radius:50%;margin-right:5px}.mrn-on{background:#21b578}.mrn-off{background:#d94b4b}.mrn-badge{padding:5px 9px;border-radius:18px;font-size:10px;font-weight:bold}.mrn-ok{background:#e7f8ef;color:#168a5d}.mrn-bad{background:#ffe9e9;color:#d23c3c}@media(max-width:700px){.mrn-stats{grid-template-columns:1fr}.mrn-head{display:block}}
</style>
<div class="breadcrumb clearfix"><ul><li><a href="index.php?app=Dashboard">Dashboard</a></li><li class="active">Servidores</li></ul></div>
<div class="mrn">
<div class="mrn-head"><div><h1>Servidores MikroTik</h1><p>Monitoramento e gerenciamento dos roteadores do provedor.</p></div><a href="?app=CadastroServidor" class="btn btn-primary"><i class="fa fa-plus"></i> Novo servidor</a></div>
<div class="mrn-stats"><div class="mrn-stat"><span>Total de servidores</span><b><?php echo $total;?></b></div><div class="mrn-stat"><span>Online</span><b class="text-success"><?php echo $online;?></b></div><div class="mrn-stat"><span>Sem comunicação</span><b class="text-danger"><?php echo $offline;?></b></div></div>
<div class="mrn-box"><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:12px"><h3 style="margin:0">Infraestrutura MikroTik</h3><input id="mrSrvBusca" class="form-control" style="max-width:330px" placeholder="Buscar servidor ou IP..."></div>
<div style="overflow:auto"><table class="table table-striped table-hover mrn-table" id="table-1"><thead><tr><th>Servidor</th><th>IP</th><th>Login</th><th>Tipo</th><th>Conectividade</th><th>Ações</th></tr></thead><tbody>
<?php if($lista) while($s=$lista->fetch_assoc()){$sock=@fsockopen($s['ip'],8728,$e,$er,1);$ok=(bool)$sock;if($sock)fclose($sock);?><tr><td><strong><?php echo htmlspecialchars($s['servidor']??'',ENT_QUOTES,'UTF-8');?></strong></td><td><?php echo htmlspecialchars($s['ip']??'',ENT_QUOTES,'UTF-8');?></td><td><?php echo htmlspecialchars($s['login']??'',ENT_QUOTES,'UTF-8');?></td><td><span class="mrn-badge mrn-ok">MIKROTIK</span></td><td><span class="mrn-dot <?php echo $ok?'mrn-on':'mrn-off';?>"></span><?php echo $ok?'Online':'Offline';?></td><td><a href="?app=Monitor&id=<?php echo base64_encode($s['id']);?>" class="btn btn-success btn-xs" title="Monitorar"><i class="fa fa-line-chart"></i></a> <a href="?app=CadastroServidor&id=<?php echo base64_encode($s['id']);?>" class="btn btn-info btn-xs" title="Editar"><i class="fa fa-pencil"></i></a> <a href="?app=Ping&id=<?php echo base64_encode($s['id']);?>" class="btn btn-warning btn-xs" title="Ping"><i class="fa fa-exchange"></i></a></td></tr><?php }?>
</tbody></table></div></div></div>
<script>document.getElementById('mrSrvBusca')?.addEventListener('input',function(){var q=this.value.toLowerCase();document.querySelectorAll('#table-1 tbody tr').forEach(function(r){r.style.display=r.innerText.toLowerCase().indexOf(q)>=0?'':'none';});});</script>
<?php } else { ?><div class="alert alert-danger"><strong>Permissão negada!</strong> Você não possui permissão para este módulo.</div><?php } ?>