<?php
if(($permissao['e1']??'N') == S){
$empresa=(int)$_SESSION['empresa'];
$lista=$mysqli->query("SELECT e.*,f.nome fabricante_nome FROM equipamentos e LEFT JOIN fabricante f ON f.id=e.fabricante WHERE e.empresa='$empresa' ORDER BY e.id DESC");
$total=$lista?$lista->num_rows:0;$disp=0;$ind=0;if($lista){$lista->data_seek(0);while($z=$lista->fetch_assoc()){if(($z['status']??'')==='S')$disp++;else$ind++;}$lista->data_seek(0);}
?>
<style>
.mre{font-family:Arial,sans-serif}.mre-head{background:linear-gradient(135deg,#17283f,#1769bd);color:#fff;border-radius:12px;padding:22px;margin-bottom:15px;display:flex;justify-content:space-between}.mre-head h1{margin:0;font-size:25px}.mre-head p{margin:4px 0 0;opacity:.8}.mre-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-bottom:15px}.mre-stat,.mre-box{background:#fff;border:1px solid #e5ebf3;border-radius:12px;padding:15px;box-shadow:0 2px 12px #17283f0d}.mre-stat span{display:block;color:#718096;font-size:11px}.mre-stat b{font-size:25px}.mre-table th{background:#f6f9fc;color:#526174;font-size:12px}.mre-table td{vertical-align:middle}.eb{padding:5px 9px;border-radius:18px;font-size:10px;font-weight:bold}.eg{background:#e7f8ef;color:#168a5d}.er{background:#ffe9e9;color:#d23c3c}@media(max-width:700px){.mre-stats{grid-template-columns:1fr}.mre-head{display:block}}
</style>
<div class="breadcrumb clearfix"><ul><li><a href="index.php?app=Dashboard">Dashboard</a></li><li class="active">Equipamentos</li></ul></div>
<div class="mre">
<div class="mre-head"><div><h1>Equipamentos</h1><p>Controle de estoque, patrimônio e disponibilidade.</p></div><a href="?app=CadastroEquipamento" class="btn btn-primary"><i class="fa fa-plus"></i> Novo equipamento</a></div>
<div class="mre-stats"><div class="mre-stat"><span>Total cadastrados</span><b><?php echo $total;?></b></div><div class="mre-stat"><span>Disponíveis</span><b class="text-success"><?php echo $disp;?></b></div><div class="mre-stat"><span>Indisponíveis</span><b class="text-danger"><?php echo $ind;?></b></div></div>
<div class="mre-box"><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:12px"><h3 style="margin:0">Inventário</h3><input id="mrEqBusca" class="form-control" style="max-width:330px" placeholder="Buscar equipamento, etiqueta ou fabricante..."></div>
<div style="overflow:auto"><table class="table table-striped table-hover mre-table" id="table-1"><thead><tr><th>Etiqueta</th><th>Equipamento</th><th>Fabricante</th><th>Nota fiscal</th><th>Status</th><th>Ações</th></tr></thead><tbody>
<?php if($lista) while($e=$lista->fetch_assoc()){?><tr><td><strong><?php echo htmlspecialchars($e['barcode']??'',ENT_QUOTES,'UTF-8');?></strong></td><td><?php echo htmlspecialchars($e['equipamento']??'',ENT_QUOTES,'UTF-8');?></td><td><?php echo htmlspecialchars($e['fabricante_nome']??'',ENT_QUOTES,'UTF-8');?></td><td><?php echo htmlspecialchars($e['notafiscal']??'',ENT_QUOTES,'UTF-8');?></td><td><?php if(($e['status']??'')==='S'){?><span class="eb eg">DISPONÍVEL</span><?php }else{?><span class="eb er">INDISPONÍVEL</span><?php }?></td><td><a href="?app=CadastroEquipamento&id=<?php echo base64_encode($e['id']);?>" class="btn btn-info btn-xs"><i class="fa fa-pencil"></i></a> <a href="app/etiqueta.php?et=<?php echo urlencode($e['barcode']??'');?>" target="_blank" class="btn btn-success btn-xs"><i class="fa fa-print"></i></a><?php if(($logado['nivel']??'')==='1'){?> <a href="?app=CadastroEquipamento&id=<?php echo base64_encode($e['id']);?>&Ex=Del" onclick="return confirm('Deseja realmente excluir este equipamento?')" class="btn btn-danger btn-xs"><i class="fa fa-trash"></i></a><?php }?></td></tr><?php }?>
</tbody></table></div></div></div>
<script>document.getElementById('mrEqBusca')?.addEventListener('input',function(){var q=this.value.toLowerCase();document.querySelectorAll('#table-1 tbody tr').forEach(function(r){r.style.display=r.innerText.toLowerCase().indexOf(q)>=0?'':'none';});});</script>
<?php } else { ?><div class="alert alert-danger"><strong>Permissão negada!</strong> Você não possui permissão para este módulo.</div><?php } ?>