<?php
if($permissao['os1'] == S){
$empresa=(int)$_SESSION['empresa'];
$ab=$mysqli->query("SELECT o.*,t.nome tecnico_nome,c.nome cliente_nome FROM ordemservicos o LEFT JOIN tecnicos t ON t.id=o.tecnico LEFT JOIN clientes c ON c.id=o.cliente WHERE o.empresa='$empresa' AND o.encerrado='N' ORDER BY o.id DESC");
$total=$ab?$ab->num_rows:0;$man=0;$inst=0;$out=0;if($ab){$ab->data_seek(0);while($z=$ab->fetch_assoc()){if(($z['situacao']??'')==='M')$man++;elseif(($z['situacao']??'')==='I')$inst++;else $out++;}$ab->data_seek(0);}
function osSit($s){return ['O'=>'Orçamento','I'=>'Instalação concluída','NI'=>'Instalação','M'=>'Manutenção','R'=>'Recuperação','A'=>'Aprovado','C'=>'Cancelada'][$s]??$s;}
function osCl($s){return ['I'=>'ok','A'=>'ok','M'=>'warn','NI'=>'blue','R'=>'violet','C'=>'bad','O'=>'blue'][$s]??'blue';}
?>
<style>
.mro{font-family:Arial,sans-serif}.mro-head{background:linear-gradient(135deg,#17283f,#1769bd);color:#fff;border-radius:12px;padding:22px;margin-bottom:15px;display:flex;justify-content:space-between}.mro-head h1{margin:0;font-size:25px}.mro-head p{margin:4px 0 0;opacity:.8}.mro-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:15px}.mro-stat{background:#fff;border:1px solid #e5ebf3;border-radius:11px;padding:15px}.mro-stat span{display:block;color:#718096;font-size:11px}.mro-stat b{font-size:23px;color:#17283f}.mro-box{background:#fff;border:1px solid #e5ebf3;border-radius:12px;padding:15px}.mro-table th{background:#f6f9fc;color:#526174;font-size:12px}.mro-table td{vertical-align:middle}.ob{padding:5px 9px;border-radius:18px;font-size:10px;font-weight:bold}.ok{background:#e7f8ef;color:#168a5d}.bad{background:#ffe9e9;color:#d23c3c}.warn{background:#fff3d8;color:#ad7200}.blue{background:#e6f1ff;color:#2565a9}.violet{background:#f0e5ff;color:#7b35b2}@media(max-width:800px){.mro-stats{grid-template-columns:repeat(2,1fr)}.mro-head{display:block}}@media(max-width:500px){.mro-stats{grid-template-columns:1fr}}
</style>
<div class="breadcrumb clearfix"><ul><li><a href="index.php?app=Dashboard">Dashboard</a></li><li class="active">Ordens de Serviço</li></ul></div>
<div class="mro">
<div class="mro-head"><div><h1>Ordens de Serviço</h1><p>Acompanhe instalações, manutenções e atendimentos em aberto.</p></div><a href="?app=CadastroOS" class="btn btn-primary"><i class="fa fa-plus"></i> Nova O.S.</a></div>
<div class="mro-stats"><div class="mro-stat"><span>Em aberto</span><b><?php echo $total;?></b></div><div class="mro-stat"><span>Manutenção</span><b class="text-warning"><?php echo $man;?></b></div><div class="mro-stat"><span>Instalações</span><b class="text-info"><?php echo $inst;?></b></div><div class="mro-stat"><span>Outros</span><b><?php echo $out;?></b></div></div>
<div class="mro-box"><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:12px"><h3 style="margin:0">Atendimentos pendentes</h3><input id="mrOSBusca" class="form-control" style="max-width:330px" placeholder="Buscar O.S., cliente ou técnico..."></div>
<div style="overflow:auto"><table class="table table-striped table-hover mro-table" id="table-1"><thead><tr><th>O.S.</th><th>Série</th><th>Técnico</th><th>Cliente</th><th>Situação</th><th>Emissão</th><th>Status</th><th>Ações</th></tr></thead><tbody>
<?php if($ab) while($o=$ab->fetch_assoc()){?><tr><td><strong>#<?php echo htmlspecialchars($o['codigo']??'',ENT_QUOTES,'UTF-8');?></strong></td><td><?php echo htmlspecialchars($o['serie']??'',ENT_QUOTES,'UTF-8');?></td><td><?php echo htmlspecialchars($o['tecnico_nome']??'Não atribuído',ENT_QUOTES,'UTF-8');?></td><td><?php echo htmlspecialchars($o['cliente_nome']??'',ENT_QUOTES,'UTF-8');?></td><td><span class="ob <?php echo osCl($o['situacao']??'');?>"><?php echo osSit($o['situacao']??'');?></span></td><td><?php echo htmlspecialchars($o['emissao']??'',ENT_QUOTES,'UTF-8');?></td><td><?php echo ($o['status']??'')==='S'?'ATIVO':'BLOQUEADO';?></td><td><a href="imprimir-ordem.php?id=<?php echo base64_encode($o['codigo']);?>" target="_blank" class="btn btn-success btn-xs" title="Imprimir"><i class="fa fa-print"></i></a> <a href="?app=CadastroOS&id=<?php echo base64_encode($o['id']);?>" class="btn btn-info btn-xs" title="Editar"><i class="fa fa-pencil"></i></a><?php if($logado['nivel']=='1'){?> <a href="javascript:void(0)" onclick="if(confirm('Deseja realmente excluir esse registro?'))location.href='?app=CadastroOS&id=<?php echo base64_encode($o['id']);?>&Ex=Del&pedido=<?php echo urlencode($o['codigo']);?>'" class="btn btn-danger btn-xs" title="Excluir"><i class="fa fa-trash"></i></a><?php }?></td></tr><?php }?>
</tbody></table></div></div></div>
<script>document.getElementById('mrOSBusca')?.addEventListener('input',function(){var q=this.value.toLowerCase();document.querySelectorAll('#table-1 tbody tr').forEach(function(r){r.style.display=r.innerText.toLowerCase().indexOf(q)>=0?'':'none';});});</script>
<?php } else { ?><div class="alert alert-danger"><strong>Permissão negada!</strong> Você não possui permissão para este módulo.</div><?php } ?>