<?php
if(!isset($_SESSION['login'])){header('Location: ../../login.php');exit;}
if(!isset($mysqli)){require_once __DIR__.'/../../config/conexao.class.php';}
if(($permissao['mk1']??S)!=S){echo '<div class="alert alert-danger"><strong>Acesso negado.</strong></div>';return;}
$empresa=(int)($_SESSION['empresa']??0);$lista=$mysqli->query("SELECT id,servidor,ip,porta FROM servidores WHERE tiporouter='MIKROTIK' AND empresa='$empresa' ORDER BY servidor");
?>
<style>
.mrx{font-family:Arial,sans-serif}.mrx-hero{background:linear-gradient(135deg,#10243e,#1c72c7);color:#fff;border-radius:16px;padding:24px;margin:10px 0 15px}.mrx-hero h1{margin:0;font-size:27px}.mrx-hero p{margin:5px 0 0;opacity:.82}.mrx-bar{display:flex;gap:9px;flex-wrap:wrap;margin-bottom:14px}.mrx-select{min-width:290px;padding:10px;border:1px solid #dbe4ee;border-radius:9px;background:#fff}.mrx-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:11px;margin-bottom:14px}.mrx-card,.mrx-panel{background:#fff;border:1px solid #e5ebf3;border-radius:13px;padding:15px;box-shadow:0 3px 15px #10243e0b}.mrx-card small{display:block;color:#718096}.mrx-card b{display:block;font-size:22px;margin-top:4px;color:#10243e}.mrx-main{display:grid;grid-template-columns:1.25fr .75fr;gap:14px}.mrx-panel h3{margin:0 0 12px;color:#10243e}.mrx-table{width:100%;border-collapse:collapse;font-size:12px}.mrx-table th{background:#f6f9fc;color:#526174}.mrx-table th,.mrx-table td{padding:9px;border-bottom:1px solid #edf2f7;text-align:left}.mrx-pill{padding:4px 8px;border-radius:15px;font-size:10px}.up{background:#e7f8ef;color:#168a5d}.down{background:#ffe9e9;color:#d23c3c}@media(max-width:950px){.mrx-grid{grid-template-columns:repeat(3,1fr)}.mrx-main{grid-template-columns:1fr}}@media(max-width:600px){.mrx-grid{grid-template-columns:repeat(2,1fr)}.mrx-select{min-width:100%}}
</style>
<div class="breadcrumb clearfix"><ul><li><a href="index.php?app=Dashboard">Dashboard</a></li><li><a href="index.php?app=Servidores">MikroTik</a></li><li class="active">Monitoramento</li></ul></div>
<div class="mrx"><div class="mrx-hero"><h1>Central de Monitoramento</h1><p>CPU, memória, uptime, PPPoE, interfaces e tráfego diretamente do RouterOS.</p></div>
<div class="mrx-bar"><select id="mrxServer" class="mrx-select"><option value="">Selecione um roteador</option><?php if($lista)while($s=$lista->fetch_assoc()){?><option value="<?php echo (int)$s['id'];?>"><?php echo htmlspecialchars($s['servidor'].' — '.$s['ip'],ENT_QUOTES,'UTF-8');?></option><?php }?></select><button id="mrxRefresh" class="btn btn-primary"><i class="fa fa-refresh"></i> Atualizar</button><a class="btn btn-default" href="index.php?app=Servidores">Servidores</a></div>
<div class="mrx-grid"><div class="mrx-card"><small>Status</small><b id="mrxStatus">—</b></div><div class="mrx-card"><small>CPU</small><b id="mrxCpu">—</b></div><div class="mrx-card"><small>Memória</small><b id="mrxMem">—</b></div><div class="mrx-card"><small>PPPoE online</small><b id="mrxPpp">—</b></div><div class="mrx-card"><small>Latência</small><b id="mrxLat">—</b></div></div>
<div class="mrx-main"><div class="mrx-panel"><h3>Interfaces</h3><div id="mrxIf">Selecione um roteador.</div></div><div class="mrx-panel"><h3>RouterOS</h3><table class="mrx-table"><tbody><tr><td>Identidade</td><td id="mrxIdn">—</td></tr><tr><td>Versão</td><td id="mrxVer">—</td></tr><tr><td>Modelo</td><td id="mrxBoard">—</td></tr><tr><td>CPU</td><td id="mrxCpuName">—</td></tr><tr><td>Uptime</td><td id="mrxUp">—</td></tr></tbody></table></div></div>
<div class="mrx-panel" style="margin-top:14px"><h3>PPPoE conectados</h3><div id="mrxPppTable">Selecione um roteador.</div></div></div>
<script>
(function(){const g=i=>document.getElementById(i),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));const bps=n=>{n=Number(n||0);if(n<1e3)return n+' bps';if(n<1e6)return(n/1e3).toFixed(1)+' Kbps';if(n<1e9)return(n/1e6).toFixed(1)+' Mbps';return(n/1e9).toFixed(2)+' Gbps';};function load(){let id=g('mrxServer').value;if(!id)return;g('mrxStatus').textContent='Consultando...';fetch('app/monitoramento/api.php?id='+encodeURIComponent(id),{cache:'no-store'}).then(r=>r.json()).then(d=>{if(!d.ok||!d.online){g('mrxStatus').textContent='Offline';g('mrxLat').textContent=d.latency_ms?d.latency_ms+' ms':'—';return;}let x=d.resource||{};g('mrxStatus').textContent='Online';g('mrxCpu').textContent=x.cpu_load==null?'—':x.cpu_load+'%';g('mrxMem').textContent=x.memory_used_percent==null?'—':x.memory_used_percent+'%';g('mrxPpp').textContent=d.pppoe_online??0;g('mrxLat').textContent=d.latency_ms+' ms';g('mrxIdn').textContent=d.server?.identity||'—';g('mrxVer').textContent=x.version||'—';g('mrxBoard').textContent=x.board||'—';g('mrxCpuName').textContent=x.cpu||'—';g('mrxUp').textContent=x.uptime||'—';g('mrxIf').innerHTML='<table class="mrx-table"><thead><tr><th>Interface</th><th>Tipo</th><th>Estado</th><th>Tráfego</th></tr></thead><tbody>'+(d.interfaces||[]).map(i=>'<tr><td>'+esc(i.name)+'</td><td>'+esc(i.type)+'</td><td><span class="mrx-pill '+(i.running?'up':'down')+'">'+(i.running?'UP':'DOWN')+'</span></td><td><button class="btn btn-xs btn-info mrxT" data-if="'+esc(i.name)+'">Consultar</button></td></tr>').join('')+'</tbody></table>';g('mrxPppTable').innerHTML='<table class="mrx-table"><thead><tr><th>Usuário</th><th>IP</th><th>Serviço</th><th>Caller-ID</th><th>Uptime</th></tr></thead><tbody>'+(d.pppoe||[]).map(p=>'<tr><td>'+esc(p.name)+'</td><td>'+esc(p.address)+'</td><td>'+esc(p.service)+'</td><td>'+esc(p.caller_id)+'</td><td>'+esc(p.uptime)+'</td></tr>').join('')+'</tbody></table>';}).catch(()=>g('mrxStatus').textContent='Erro');}g('mrxServer').addEventListener('change',load);g('mrxRefresh').addEventListener('click',load);document.addEventListener('click',e=>{if(e.target.classList.contains('mrxT')){let id=g('mrxServer').value,inf=e.target.dataset.if;fetch('app/monitoramento/api.php?id='+id+'&action=traffic&interface='+encodeURIComponent(inf),{cache:'no-store'}).then(r=>r.json()).then(d=>alert(d.ok?'Interface '+inf+'\nRX: '+bps(d.rx_bps)+'\nTX: '+bps(d.tx_bps):d.error));}});})();</script>
