<?php
if(($permissao['mk1']??'N') == S){
$empresa=(int)$_SESSION['empresa'];
$lista=$mysqli->query("SELECT id,servidor,ip,login,tiporouter FROM servidores WHERE empresa='$empresa' ORDER BY servidor");
?>
<style>
.mrm{font-family:Arial,sans-serif}.mrm-head{background:linear-gradient(135deg,#17283f,#1769bd);color:#fff;border-radius:12px;padding:22px;margin-bottom:15px}.mrm-head h1{margin:0;font-size:25px}.mrm-head p{margin:4px 0 0;opacity:.8}.mrm-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:15px}.mrm-card{background:#fff;border:1px solid #e5ebf3;border-radius:12px;padding:15px;box-shadow:0 2px 12px #17283f0d}.mrm-card span{display:block;color:#718096;font-size:11px}.mrm-card b{display:block;font-size:22px;color:#17283f;margin-top:5px}.mrm-list{background:#fff;border:1px solid #e5ebf3;border-radius:12px;padding:15px}.mrm-row{display:grid;grid-template-columns:1.4fr 1fr .8fr .8fr 1fr;gap:10px;align-items:center;padding:13px 5px;border-bottom:1px solid #edf1f5;font-size:13px}.mrm-row:last-child{border:0}.dot{width:9px;height:9px;border-radius:50%;display:inline-block;margin-right:6px}.on{background:#20b577}.off{background:#d94b4b}.badge{padding:5px 9px;border-radius:15px;font-size:10px;background:#e6f1ff;color:#2565a9}@media(max-width:800px){.mrm-grid{grid-template-columns:repeat(2,1fr)}.mrm-row{grid-template-columns:1fr 1fr}.mrm-row>div:nth-child(4),.mrm-row>div:nth-child(5){grid-column:auto}}@media(max-width:500px){.mrm-grid{grid-template-columns:1fr}}
</style>
<div class="breadcrumb clearfix"><ul><li><a href="index.php?app=Dashboard">Dashboard</a></li><li class="active">Monitoramento de Rede</li></ul></div>
<div class="mrm"><div class="mrm-head"><h1>Monitoramento de Rede</h1><p>Visão operacional dos roteadores MikroTik cadastrados.</p></div>
<div class="mrm-grid"><div class="mrm-card"><span>Roteadores</span><b id="mrmTotal">0</b></div><div class="mrm-card"><span>Online</span><b class="text-success" id="mrmOnline">0</b></div><div class="mrm-card"><span>Offline</span><b class="text-danger" id="mrmOffline">0</b></div><div class="mrm-card"><span>Última verificação</span><b id="mrmHora" style="font-size:16px">--:--:--</b></div></div>
<div class="mrm-list"><div class="mrm-row" style="font-weight:bold;background:#f7f9fc"><div>Servidor</div><div>IP</div><div>Status</div><div>Latência</div><div>Ação</div></div>
<?php if($lista) while($s=$lista->fetch_assoc()){?><div class="mrm-row mrm-server" data-id="<?php echo (int)$s['id'];?>"><div><strong><?php echo htmlspecialchars($s['servidor']??'',ENT_QUOTES,'UTF-8');?></strong></div><div><?php echo htmlspecialchars($s['ip']??'',ENT_QUOTES,'UTF-8');?></div><div><span class="dot off"></span><span class="mrm-status">Verificando</span></div><div class="mrm-lat">--</div><div><a class="btn btn-info btn-xs" href="?app=CadastroServidor&id=<?php echo base64_encode($s['id']);?>"><i class="fa fa-pencil"></i></a></div></div><?php }?>
</div></div>
<script>
(function(){var rows=[].slice.call(document.querySelectorAll('.mrm-server'));function check(){var on=0,off=0,done=0;rows.forEach(function(row){fetch('api.php?id='+row.dataset.id,{cache:'no-store'}).then(function(r){return r.json()}).then(function(d){var ok=d.ok&&d.connectivity&&d.connectivity.online;var dot=row.querySelector('.dot'),st=row.querySelector('.mrm-status');dot.className='dot '+(ok?'on':'off');st.textContent=ok?'Online':'Offline';row.querySelector('.mrm-lat').textContent=ok?d.connectivity.latency_ms+' ms':'--';if(ok)on++;else off++;}).catch(function(){row.querySelector('.mrm-status').textContent='Erro';off++}).finally(function(){done++;if(done===rows.length){document.getElementById('mrmTotal').textContent=rows.length;document.getElementById('mrmOnline').textContent=on;document.getElementById('mrmOffline').textContent=off;document.getElementById('mrmHora').textContent=new Date().toLocaleTimeString();}})});}check();setInterval(check,30000)})();
</script>
<?php } else { ?><div class="alert alert-danger"><strong>Permissão negada!</strong> Você não possui permissão para este módulo.</div><?php } ?>